spring:
  flyway:
    schemas: users
    table: schema_version
    baselineOnMigrate: true
    validateOnMigrate: true
    enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:5434/${DB:jooq}?currentSchema=jooq
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    type: com.zaxxer.hikari.HikariDataSource
